### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Noura-Na1513399** [cmps312f21/cmps312-content#1]
![image](https://user-images.githubusercontent.com/89040486/129955182-31f399e4-c889-4c8f-9964-6b66b47087e7.png) 

They all have ( set0f (1,2,3) ) why is false ?! or is it because they have different names ( set1 and set2 ) ?
Thanks

**Comment by erradi** [comment]
Dear @Noura-Na1513399,
First set1 and set2 are 2 different and distinct objects (they occupy different memory locations).
If we compare them using === we will get false since they are distinct variables referencing 2 different objects.
=== will only be true if both the variables are pointing to the same object.
On the other hand, == operator is used to compare the values of two variables. It be true if the values and data type match.
More info @ https://www.baeldung.com/kotlin/equality-operators
